import json,hashlib,glob
from pathlib import Path
import numpy as np,pandas as pd
O=Path(__file__).parent
rows=json.load(open(O/'grid2_results.json'));audit=json.load(open(O/'grid2_audit.json'));ha=json.load(open(O/'hour2_audit.json'));hr=json.load(open(O/'hour2_results.json'))
ctrl=np.load(O/'grid2_controls.npz');dates=pd.to_datetime(ctrl['t'],unit='ms',utc=True)
def sh(r):return r.mean()/r.std(ddof=1)*np.sqrt(365)
def mean(e,key):return np.mean([p[key] for p in e['phases']])
def f(v):return f'{v:.4f}'
lines=['# 移动止盈网格：最终报告（当前本地数据）','', '**结论：18 组均不可用。** 逐币的改善在两种日内触发规则间翻转，收盘规则下全部 Δ 为负、2023–24 全部为负；全仓组全部配对 Δ 为负、FWER 不通过。没有一组同时满足用户事先给定的四条标准。对交接中“1343 日、2023-04 起”的指定样本及真正盘中全仓移动止盈，证据不足；本报告不冒充那份样本的结果。','', '## 数据与基线复核','',f"实际读取 `/tmp/hl-daily-full/*.json`，234 币、{audit['days']} 个不同日线日期，{audit['start']} → {audit['end']}；扣除前 33 日后主检验 1192 日。229 币 ≥100 根，所有币内部相邻日期零缺口。短历史币："+', '.join(f"{c} {v['count']} 根" for c,v in audit['short'].items())+'。这与用户已核实的五个新上市币一致；本次数据检查验证长度与内部连续性，不独立证明上市事件。','', '**未确认交接所称 1343 日和 2023-04 起点**：当前文件及 `retrieval/request.json` 的日线起点为 2023-06-01，不能静默写成数据一致。仅连续性通过也不表示退市后仍有可交易价格；本地持仓缺价诊断见下。','', '用户给定基线保留如下；已读代码复核口径：20 日波动含当日、fee 0.0007、gross 2.7、流动性 5e6、无 funding。**数值来自用户的已跑结果，本次未重新运行原始基线入口，不能声称数字已独立复现。** 不尝试复现 1.62。','', '| 参考基线 | 全样本 Sharpe | 2023–24 | 2025–26 |','|---|---:|---:|---:|','| cap5_open_0.0007 | 1.1766 | -0.2767 | 2.4452 |','| cap5_close_0.0007 | 1.1816 | — | — |','| cap8_open_0.0007 | 1.1437 | — | — |','', '为了得到逐日配对检验，在移动止盈引擎内保留无止盈的同步控制。它沿用原引擎开盘调仓，但每日收盘计净值；不会写回原基线文件。这不是对参考 Sharpe 的搜索复现。既有 `baseline_results.json` / `baseline_exact_recheck.json` 也与用户数字不同，故不能拿它们当指定参考的配对收益。','', '| 起点偏移（日） | 控制 Sharpe | 2023–24 | 2025–26 |','|---|---:|---:|---:|']
for s in range(3):
 r=ctrl[f'r{s}'];d=dates[s:];lines.append(f'| {s} | {f(sh(r))} | {f(sh(r[d.year<=2024]))} | {f(sh(r[d.year>=2025]))} |')
lines+=['','由于数据和计净值时刻均不相同，下表主 Δ、p、相关性均相对**同步控制**；额外列出与用户 1.1766 的数值差，但这个差不用于显著性或资格判定。','', '## 实现与预设判定','', '直接复用 `baseline.py` 中的加载、信号与 target，保留开盘调仓、szDecimals 向下取整、10 美元最小单、2% 调仓带、双向名义 2.7 倍和净额交易成本。预计算权重使用大额账户 cap=5；本实验不研究微型账户动态 cap。新增 `baseline.py --trailing-grid` 入口，不运行旧的四档基线 main。没有修改 `src/`，没有 commit/push/部署或实盘操作；工作区原已存在 `src/live.rs` 修改，本任务未碰它。','', '逐币：第一次持仓/反向时设置入场成本，增加仓位更新加权成本并保持已观察到的峰值价格；减仓保留入场基准。多头用高点更新峰值、低点判断回撤，空头用低点/高点对称处理。激活是价格相对加权入场成本的有利变化达到阈值；距离是从有利峰值价格回撤的百分比，不是账户杠杆收益百分比。触发后清仓，剩余日内不再重入；下一日开盘正常参与目标调仓，重开再次付费。','', '悲观（low）情景：假设日内先到有利峰值、再到不利极值并触发止盈，多头用 low、空头用 high 判触发；成交按止盈阈值，已激活仓位开盘越过旧阈值时按不利开盘价成交。**low 用于判断触发，不把整根最低价冒充常规止盈成交价。** 乐观（close）情景：同一日只以收盘判触发、收盘成交。不触发仓位按收盘净值继续持有。每笔主动退出单边成本均为 0.070%（0.045% fee + 0.025% 滑点）；常规调仓同成本，反向成本按两腿名义。','', '这两种规则是用户指定的**路径情景**，不是数学意义下任意真实路径的收益上下界；止盈会截断后续上涨，所以叫“悲观”的先触发规则也可能收益更高。逐日 high/low 仍不能证明极值先后顺序，且阈值成交是假设市场订单在触发附近执行加固定滑点；跳空、深度及极端滑点不能由 OHLC 证实。若两端翻转，直接否决，不挑高端。','', '全仓：峰值只由**所有持仓在同一 UTC 日收盘同步重估的净值**更新，净值基准为初始净值或上次全仓退出后净值，包含此前已付成本。不是各币 high/low 的拼接，不是每日重设基准。达到激活且同步净值从峰值回撤超过距离时，同时对有有效报价的币按收盘清仓；缺价仓位保留，全部平仓后才重设峰值基准。日报两端因此相同，只表示收盘采样模型相同，**真实盘中悲观端无法识别**；不能把这个退化区间说成稳健。小时验证改用同步小时收盘净值，同样不拼极值。','', '资格标准原样采用用户指令：p_fwer < 0.05；两个子区间策略净 Sharpe 均正且相对控制均改善；改进大于相位噪声；悲观端改进仍正。另按明确要求，两端结论翻转视为不显著。任何一条不满足均不可用。','', '## 相位、统计与完整网格','', '重要口径：原 `baseline.py` 为每天开盘调仓（`rebalance_slices=1`），不存在多个日历余数相位。这里只能穷尽**一个实际日历相位**，另报告起点偏移 0/1/2 日的均值、标准差和范围；这三个起点不是三天错峰调仓，也不伪称“多相位验证通过”。真正多时刻日内调仓需要完整小时数据/对应控制。起点离散度仅作诊断，本任务要求的多相位证据并未满足。','', '配对循环 block bootstrap：块长 30 日、4999 次、随机种子 20261009，重采样策略/控制相同日期，统计量是全样本 Sharpe 差，以中心化 bootstrap 差分布作单侧改善检验。Δ≤0 设 p=1。每端报告三起点 p 的最大值，再 Bonferroni ×108（18 组 ×3 起点 ×2 路径情景），全仓重复端也计入，保守控制家族错误率。p 最小分辨率 1/5000；近阈值结果有 Monte Carlo 误差，未用其选择参数。未进行 i.i.d. t 检验。检验的有效样本是每日净收益而非重叠的持仓事件。','', '表中 A/D 为激活/回撤%；“前/后”均为三个起点的子区间 Sharpe 均值；p/FWER 为两端各自最差起点；区间按 **low → close** 顺序列示，不能假定左数必然小于右数。','', '| 模式 | A/D | Sharpe low→close | Δ配对控制 low→close | Δ参考1.1766 low→close | 2023–24 low→close | 2025–26 low→close | p low→close | p_fwer low→close | 判定 |','|---|---|---:|---:|---:|---:|---:|---:|---:|---|']
for x in rows:
 lo=x['ends']['low'];hi=x['ends']['close'];pair=lambda fun:f'{f(fun(lo))} → {f(fun(hi))}'
 lines.append('| '+('逐币' if x['mode']=='coin' else '全仓收盘')+f" | {x['activation']:.0%}/{x['distance']:.0%} | "+' | '.join([pair(lambda e:e['mean_sharpe']),pair(lambda e:e['mean_delta']),pair(lambda e:e['mean_sharpe']-1.1766),pair(lambda e:mean(e,'early')),pair(lambda e:mean(e,'late')),pair(lambda e:e['p']),pair(lambda e:e['p_fwer'])])+' | 不可用 |')
lines+=['','### 起点离散度、成本、换手及相关性','', '各值仍为 low→close。成本为实际扣除的费用/日初净值的年化均值，包含常规调仓和主动止盈；换手为单日成交名义/净值。相关性为日收益与同步控制的 Pearson 相关。范围是三起点 Δ 的 max−min。','', '| 模式 | A/D | Δ标准差 | Δ范围 | 年化成本 | 日换手 | 与控制相关性 | 日线持仓缺价日数（起点0） |','|---|---|---:|---:|---:|---:|---:|---:|']
for x in rows:
 es=[x['ends'][s] for s in ['low','close']];pairs=lambda fun:' → '.join(f(fun(e)) for e in es)
 lines.append(f"| {'逐币' if x['mode']=='coin' else '全仓收盘'} | {x['activation']:.0%}/{x['distance']:.0%} | "+' | '.join([pairs(lambda e:e['sd_delta']),pairs(lambda e:np.ptp([p['delta'] for p in e['phases']])),pairs(lambda e:mean(e,'annual_cost')),pairs(lambda e:mean(e,'turnover')),pairs(lambda e:mean(e,'correlation'))])+f" | {es[0]['phases'][0]['missing']} → {es[1]['phases'][0]['missing']} |")
lines+=['','## 小时线真实触发检查','',f"冻结已读取的 234 币小时数据（`hour2_candles_snapshot.npz`），仅使用 BTC 有完整 24 个小时的日期：{ha['start']} → {ha['end']}，{ha['days']} 日、{ha['hours']} 小时。各币文件长度 {ha['min_rows']}–{ha['max_rows']} 根，同步面板缺价单元 {ha['missing_cells']} 个（包括尚未上市/退市币和抓取不足，不等同于这些币均有持仓）。持仓缺价逐组统计如下。",'', '在小时样本前以对应日线规则预热持仓、峰值、入场成本，在样本内每小时顺序推进；调仓仍每天开盘。逐币的触发只能在已观察小时 OHLC 内确认跨越阈值；一小时内极值顺序仍未知。全仓用同步小时收盘净值触发。缺小时价保留最后价，不将空白当作可成交价；因此存在持仓缺价的结果只是**不完整价格路径诊断**，不能称完整真实成交验证。以下 Sharpe 仅计算 92 日，未做独立 OOS，也未用于重新选择参数。','', '| 模式 | A/D | 小时样本 Sharpe low→close | Δ同期控制 low→close | 持仓缺小时标记次数 low→close |','|---|---|---:|---:|---:|']
for x in hr:
 es=[x['ends'][s] for s in ['low','close']]
 lines.append(f"| {'逐币' if x['mode']=='coin' else '全仓小时收盘'} | {x['activation']:.0%}/{x['distance']:.0%} | "+' → '.join(f(e['sharpe']) for e in es)+' | '+' → '.join(f(e['delta']) for e in es)+' | '+' → '.join(str(e['missing_marks']) for e in es)+' |')
lines+=['', '缺价次数字段同时包含前期日线缺价日诊断与样本期“持仓×小时”缺价次数，完整明细见 JSON；不能把它解释成独立缺口事件数。短样本能检验逐小时更新/止盈/下一日重开的机械行为，并显示日线情景结果未必可迁移；它不能证明三年稳健性、完整市场订单成交价、日线两个子区间均改善，亦不能修复本地数据与参考基线的差异。','', '## 判定与局限','', '逐币参数即使 low 端校正 p 通过，也不能合格：close 端配对改善为负且早期子区间为负，两端改善符号翻转。其余逐币组至少显著性/子区间不通过。全仓收盘组全部 p_fwer=1、配对 Δ<0，早期子区间为负，且真实日内悲观端未知。因此没有“可用”配置。','', '此外，指定全样本与本地文件不一致、真正多日内时刻相位未验证、退市/缺价仍保留陈旧估值、小时线不完整、固定滑点和阈值成交不含深度/跳价、block 长度未做广泛敏感性检验，均限制推断。本报告的“不可用”是本次候选未过门槛，不是证明所有移动止盈永远无效。不能把失败候选换阈值、换时段、换成本后称同一预注册实验通过。','', '## 产物与复跑','', '所有计算每个参数/端点/起点单独写 NPZ，并每完成一组刷新 JSON；已有原基线产物不覆盖。主要文件：`grid2.py`、`grid2_results.json`、`grid2_controls.npz`、`grid2_audit.json`、`hour2.py`、`hour2_results.json`、`hour2_audit.json`、`hour2_candles_snapshot.npz`、`REPORT2_manifest.json`。','', '按用户指定 Python，在 `/Users/wonder/Code/stars` 执行：','', '```sh','/Users/wonder/.dsh/dsh-runtimes/dsh-primary-runtime/dependencies/python/bin/python3 research/trailing_tp_20261008/baseline.py --trailing-grid','/Users/wonder/.dsh/dsh-runtimes/dsh-primary-runtime/dependencies/python/bin/python3 research/trailing_tp_20261008/hour2.py','/Users/wonder/.dsh/dsh-runtimes/dsh-primary-runtime/dependencies/python/bin/python3 research/trailing_tp_20261008/report2_build.py','```','', '复跑会读取当时的 `/tmp` 文件；精确复核本次小时路径请使用冻结快照，不将仍在抓取的文件视为固定数据。']
(O/'REPORT2.md').write_text('\n'.join(lines)+'\n')
paths=glob.glob('/tmp/hl-daily-full/*.json')+[str(O/p) for p in ['baseline.py','grid2.py','hour2.py','report2_build.py','grid2_results.json','grid2_controls.npz','grid2_audit.json','hour2_results.json','hour2_audit.json','hour2_candles_snapshot.npz','REPORT2.md']]+['src/trader.rs','docs/validation-protocol.md']
(O/'REPORT2_manifest.json').write_text(json.dumps({p:hashlib.sha256(Path(p).read_bytes()).hexdigest() for p in paths},indent=2))
