import json,pathlib,datetime
import numpy as np
O=pathlib.Path(__file__).resolve().parent
x=json.loads((O/'results.json').read_text());s=x['summary'];meta=x['meta'];sens=json.loads((O/'sensitivity.json').read_text());api=json.loads((O/'api_evidence.json').read_text());cov=json.loads((O/'coverage.json').read_text())
fmt=lambda t:datetime.datetime.fromtimestamp(t/1000,datetime.timezone.utc).strftime('%Y-%m-%d %H:%M')
rows=[]
(O/'raw'/'merged').mkdir(parents=True,exist_ok=True)
for c in cov:
 old=json.loads((pathlib.Path('/tmp/hl-hist')/(c['coin']+'.json')).read_text());f=O/(c['coin']+'_recent.json');new=json.loads(f.read_text()) if f.exists() else []
 union={int(z['t']):z for z in old+new};t=sorted(union)
 (O/'raw'/'merged'/(c['coin']+'.json')).write_text(json.dumps([union[u] for u in t]))
 rows.append(dict(coin=c['coin'],cached_hours=c['hours'],fetched_hours=len(new),merged_hours=len(t),first=fmt(t[0]),last=fmt(t[-1]),missing=int((t[-1]-t[0])//3600000+1-len(t)),liquid=c['liquid'],volume=c['mean_daily_dvol_30d']))
(O/'merged_coverage.json').write_text(json.dumps(rows,indent=2))
lines=['# 提高调仓频率的独立验证：未通过','', '**最终判断：没有足够证据支持提高频率；不建议据此改实盘。两年小时线拉不到，长样本验证未完成。** 这不是已证明高频永远无效，也不能宣称已证伪原来的 +0.49。可取得数据只覆盖 2026 年约 213 天；本报告的收益统计是独立的 206 天诊断，不能替代要求的至少两年验证。','', '## 1. 数据限制：分页不能恢复被滚动删除的小时线','', '已先阅读 docs/validation-protocol.md 和 src/trader.rs。官方 [Info endpoint 文档](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint#candle-snapshot) 明确写明只提供最近约 5000 根 candle。startTime/endTime 是保留窗口内的范围筛选，不能绕过保留限制。实测记录见 api_evidence.json，保留请求 payload、返回根数、边界与抓取时间。','', f'共执行 {len(api)} 个 API 请求，无最终失败；BTC/ETH/SOL 各做三年起点请求、最早根之前的反向分页，以及 2023/2024/2025 年 10 月独立窗口。12 个旧窗口全部返回空，而近期请求各返回约 5000 根。对缓存 81 币按截至 2026-10-03 前 30 个完整 UTC 日的平均每日成交额（小时 v×c 求和）>$500 万筛出 43 币，均重新拉取三年范围并保留实际返回。下载宇宙是已有缓存中的当前液态币，不能声称涵盖历史上所有退市币。','', '新拉取的常见边界约 2026-03-14 至 2026-10-08；旧缓存早约五天，两者合并只能得到约 213 天，并非两年。每币实际覆盖表见末尾；新币有更短覆盖，未填充上线前数据。旧缓存的 81 币也并非每币都有 5004 小时。','', '官方 [历史数据说明](https://hyperliquid.gitbook.io/hyperliquid-docs/historical-data) 表明 archive S3 不直接提供 candles；有 L2/asset contexts，另有节点 fills/trades。重建同所逐笔成交 OHLCV 是另一条可能路线，但本次没有取得并验证两年完整逐笔数据，不能用其他交易所价格、日线插值或 L2 mid 冒充 Hyperliquid 小时成交线。','', '## 2. 冻结口径与相位','', '严格隔离调仓频率：14 日收益/20 日样本标准差、负波动、当日成交额/此前 30 日均值；逐因子各自 top/bottom 等权，三张权重平均后 Σ|w|=1。top_frac=0.2，单因子每腿 cap=8，点时流动性门槛平均日成交额 $500 万。按 trader.rs 的日线 v×c 计算信号成交额，流动性均值排除信号当日；波动含信号当日。','', '最近已收盘 UTC 日线决定目标，日内重复执行同一目标并按当时权益和价格重新定仓；没有改为滚动 24h 日线，也没有加入日内新信号。无止盈、无错峰（slices=1），gross 目标=0.9×3×equity=2.7×equity，沿用源码 2% 目标仓位调仓带。cap=8 是每个因子每腿的上限；三因子叠加后总腿币数可能超过 8，若把总腿截成 8 则会改变原权重算法，本次未这样做。','', '频率 1/1.5/2/3/4× 对应每 24/16/12/8/6 小时。以 UTC epoch 整点为锚，分别枚举 24/16/12/8/6 个真正不同的小时起点，共 66 相位。特别是每 12h 的 0h 与 12h、每 8h 的 0h/8h/16h，本质上是同一个循环；重复它们无法检测相位敏感性。1.5× 是每 16h，48 小时内 3 次，而非任选每天多一单。','', f'固定诊断窗口：{meta["start"]} 至 {meta["last_day"]}，{meta["days"]} 个完整 UTC 交易日，最后统一清仓。使用 43 币旧小时缓存和本地日线完整历史作预热；新下载数据用于验证覆盖上限，未事后改变诊断窗口。当前液态宇宙选择有幸存者偏差，所有频率使用同一宇宙；这是短样本诊断的又一限制。','', '小时开盘为执行基准代理，后续小时开盘逐时盯市，真实数量持仓漂移、权益复利、每笔买卖绝对名义收费，反手付双向成本；不是每小时把权重自动归一。taker 4.5bp 加给定滑点，开始建仓和最终清仓均收费。断言所需目标、持仓及下一小时价格不缺失，目标净和为零，每相位逐小时累计收益与终值权益一致，且权益始终为正。没有小账户本金，未模拟 $10 最小订单、$15 持仓门槛和交易数量精度；资金费、盘口容量/IOC 拒绝、强平也未建模，因此“净”仅指扣所列手续费与滑点后的价格收益。','', '## 3. 所有滑点档位：相位平均 Sharpe（短样本）','', '|频率|2bp|3bp|5bp|8bp|12bp|20bp|','|---|---:|---:|---:|---:|---:|---:|']
for n in ['1x','1.5x','2x','3x','4x']:lines.append('|'+n+'|'+'|'.join(f'{s[f"{n}_{v:.4f}"]["full"]["sharpe"]:.3f}' for v in [.0002,.0003,.0005,.0008,.0012,.002])+'|')
lines+=['','Sharpe 使用每日复合净收益、√365 年化；主统计是各相位 Sharpe 的算术平均，并非先平均收益再算一个 Sharpe。未复现原两段 93 天的 2.32/2.81，不混用其宇宙、信号时钟或执行模型。','','|频率（3bp）|平均 Sharpe|较每日 Δ|相位 SD|相位范围 max−min|判定|','|---|---:|---:|---:|---:|---|']
b=s['1x_0.0003']['full']['sharpe']
for n in ['1x','1.5x','2x','3x','4x']:
 v=s[n+'_0.0003']['full'];lines.append(f'|{n}|{v["sharpe"]:.3f}|{v["sharpe"]-b:+.3f}|{v["phase_sd"]:.3f}|{v["phase_range"]:.3f}|'+('基线' if n=='1x' else 'SD 大于改善，噪声/否决')+'|')
lines+=['','全部逐相位 Sharpe 保存在 results.json，不隐藏差相位。所有高频档均未通过相位门槛。','','## 4. 成本交叉点','','以所有频率使用**同一固定滑点**为定义，求相位平均 Sharpe 与每日相等的位置。对 0–40bp 区间用完整权益/成本重模拟二分；这些是样本内模型交叉点，没有长期有效性或精确阈值保证。','','|频率|共同滑点交叉点|说明|','|---|---:|---|']
for n,v in sens['crossings'].items():
 q=v.get('common_slippage_crossing');lines.append(f'|{n}|{q*100:.3f}%（{q*1e4:.2f}bp）|'+('超出指定 20bp 网格，仅补充模型敏感性' if q>.002 else '指定网格内')+'|')
lines+=['','4× 的点估计优势约在 5.7bp 消失，3× 在约 11.7bp；1.5×/2× 到 20bp 仍可能有相对点估计优势，但双方 Sharpe 已负，不能解释为可赚钱或可上线。没有可靠的实盘交叉点可报告。','','本诊断并非“仅 ≤0.03% 才成立”：某些点估计在更高固定滑点仍为正差；但相位门槛、全期 FWER 和长样本门槛均失败。若未来合格长样本只在 ≤3bp 成立，应明确判为实盘不可用；目前不能拿单个共同成本曲线证明可用。','','## 5. 每周 0.025% 不能直接外推到日内','','0.025% 是用户提供的每周调仓实测锚，本次未取得逐笔成交验证。单笔滑点受订单/市场成交量参与率、深度、波动和执行时长影响，调仓次数增多不必然使每笔订单变大（更小的拆单也可能减少冲击），但增加总付费主动成交。不能无条件假定每单仍是 2.5bp。','','依据 [Durin/Rosenbaum/Szymanski 的平方根冲击研究](https://arxiv.org/abs/2311.18283)，采用一个明确的**压力假设**：同本金、相近波动与市场成交量/执行条件下，把年化主动换手 T 当作持续参与率的粗代理，s(T)=s_floor+(2.5bp−s_floor)√(T/T_week)。这不是已拟合的 HL 定律；聚合换手无法识别每币每单参与率，也不把股票市场参数当加密实测值。需要逐笔成交、执行前 mid、订单额/同期成交量才能校准。','','T_week 用同一冻结信号/执行模型的每 168 小时调仓枚举 168 起点估算，仅用于成本锚，不参与收益候选筛选。'+f' T_week≈{sens["weekly_turnover"]:.1f} 倍权益/年；日频到 4× 的主动换手并未随频率线性增长，因为日内目标冻结，主要新增漂移修正。','','|成本假设|频率|假设滑点 bp|Sharpe|较相同假设的每日 Δ|','|---|---|---:|---:|---:|']
for model,vals in sens['models'].items():
 for n,v in vals.items():lines.append(f'|{model}|{n}|{v["slippage"]*1e4:.2f}|{v["sharpe"]:.3f}|{v["delta_vs_daily"]:+.3f}|')
lines+=['','带 1bp 固定部分时，换手代理把日频滑点提高到约 4bp，4× 的优势几乎归零；纯平方根时到约 5bp，4× 低于每日。2× 仍有小幅点估计优势，不能诚实地说所有高频优势已被真实滑点消灭；但这些都不显著且相位不稳。若主动换手确实增至原来的 2–4 倍，纯平方根假设给出 3.54–5.00bp，而非维持 2.5bp。实盘改为日内重算信号可能有更大换手，本报告的冻结信号数值不能外推给该策略。','','## 6. 三个子区间（3bp；其他成本每段见 results.json）','','|频率|段 1 Sharpe|段 2 Sharpe|段 3 Sharpe|','|---|---:|---:|---:|']
for n in ['1x','1.5x','2x','3x','4x']:lines.append('|'+n+'|'+'|'.join(f'{s[n+"_0.0003"][f"segment_{i}"]["sharpe"]:.3f}' for i in [1,2,3])+'|')
for part in ['segment_1','segment_2','segment_3']:
 lines+=['',f'### {part}：全部成本档位 Sharpe','', '|频率|2bp|3bp|5bp|8bp|12bp|20bp|','|---|---:|---:|---:|---:|---:|---:|']
 for n in ['1x','1.5x','2x','3x','4x']:lines.append('|'+n+'|'+'|'.join(f'{s[f"{n}_{v:.4f}"][part]["sharpe"]:.3f}' for v in [.0002,.0003,.0005,.0008,.0012,.002])+'|')
lines.append('')
for label,v in meta['segments'].items():
 if label!='full':lines.append(f'- {label}: {v[0]} → {v[1]}，{v[2]} 天。')
lines+=['','这些都是同一年内约两个月的段，不是协议要求的 2023–24 / 2025–26 两种长期环境。段内改善不能冒充跨年份稳健。','','## 7. 块 bootstrap + maxT','','固定家族：4 个高频备择 × 6 个成本 ×（全期+3 子段）= **96 个方向性假设**。5 频率含基线，30 个频率/成本配置，66 个相位×6 成本=396 条主回测。各相位是同一候选的组成，不是 396 个独立样本。成本根求解及两种冲击场景是敏感性描述，未另筛收益假设。','','每日收益上的配对 Sharpe 影响函数，先对每相位计算后平均；中心化环形移动块 bootstrap 4999 次。每个区间内 24 个备择共用日期索引并取 studentized maxT；四个区间的 maxT p 再 Bonferroni×4，控制整个 96 检验家族，不假定子段和全期独立。固定块长 7/14/30 天全部报告，不挑最有利块长。这是影响函数渐近近似，小样本尾部 p 不能视为精确检验。','','|块长|全期最低 p_fwer|家族所有检验最低 p_fwer|','|---|---:|---:|']
for bl,rs in x['bootstrap'].items():lines.append(f'|{bl} 天|{min(v["p_fwer"] for v in rs if v["segment"]=="full"):.4f}|{min(v["p_fwer"] for v in rs):.4f}|')
lines+=['','全部全期检验 p_fwer=1，未通过。30 天块仅段 1 的 1.5×/2bp 出现 p_fwer≈0.044，14 天块不通过且 7 天块更不通过；约 68 天子段仅约两个 30 天块，结果明显依赖块长。它是段内现象，不能覆盖全期失败，更不能抵消相位与长样本失败。','','## 8. 敞口、换手、成本（3bp）','','净敞口比例在每小时盯市后、当小时调仓前观测，跨相位/小时汇总；不只在目标净敞口恰好为零的调仓后测量。','','|频率|平均 \\|net\\|/gross|P90|最大|年化单边成交名义/权益（倍）|年化费用/权益|费用/毛价格收益|','|---|---:|---:|---:|---:|---:|---:|']
for n in ['1x','1.5x','2x','3x','4x']:
 a=s[n+'_0.0003'];e=a['exposure'];f=a['full'];lines.append(f'|{n}|{e["mean"]:.3%}|{e["p90"]:.3%}|{e["max"]:.3%}|{f["annual_turnover"]:.1f}|{f["annual_cost"]:.2%}|{f["cost_over_gross"]:.2%}|')
a=np.load(O/'daily_returns.npz');corr={n:float(np.corrcoef(a[n+'_0.0003'].mean(axis=0),a['1x_0.0003'].mean(axis=0))[0,1]) for n in ['1.5x','2x','3x','4x']}
lines+=['','与每日基线的日收益相关性（3bp，各频率先平均相位收益，只作相关性描述）：'+', '.join(f'{n}={v:.4f}' for n,v in corr.items())+'。','', '换手定义为 Σ|交易名义|/交易前权益，买与卖分别计入，年化均值×365；不是除以 gross，也不是双边除以二。费用比例分母为小时毛价格 P&L/权益累加的算术年化，不是 CAGR 或扣费后收益；按净收益作分母会夸大/翻转比例。每日复合净收益的年化算术值另存 results.json，因日内复合，不能机械当作毛小时累计−费用。','','高频确实减少漂移：4× 平均净比例约为每日的 60%。这里只改调仓，不加新因子，所以可能机制是更早执行当天目标、控制 drift/gross、路径上的复利变化；尚无因果分解，不能声称“只是”净漂移，也不能把漂移下降自动等同 Sharpe 显著提高。','','## 9. 覆盖明细（UTC）','','下表是旧缓存与本次新抓取按 t 去重的实际并集。只有液态 43 币重新拉取，其他 38 币保留旧覆盖；空旧窗无法增加历史。missing 是首尾间缺失小时数，未填补。30d 成交额是下载筛选锚，不是回测未来可知的固定流动性条件；回测另按每个历史时点筛选。','','|币|液态|旧小时|新返回|并集小时|起点 UTC|终点 UTC|缺小时|30d 均日额 $M|','|---|---|---:|---:|---:|---|---|---:|---:|']
for r in rows:lines.append(f'|{r["coin"]}|{"是" if r["liquid"] else "否"}|{r["cached_hours"]}|{r["fetched_hours"]}|{r["merged_hours"]}|{r["first"]}|{r["last"]}|{r["missing"]}|{r["volume"]/1e6:.2f}|')
lines+=['','## 10. 复现与最终决策','','```bash','cd /Users/wonder/Code/stars','python3 research/frequency_20261008/fetch.py','OPENBLAS_NUM_THREADS=1 /Users/wonder/miniconda3/bin/python research/frequency_20261008/analyze.py','OPENBLAS_NUM_THREADS=1 /Users/wonder/miniconda3/bin/python research/frequency_20261008/sensitivity.py','/Users/wonder/miniconda3/bin/python research/frequency_20261008/report.py','```','','脚本依赖 numpy/pandas；下载脚本内设置指定代理，逐请求间隔、失败指数退避最多 4 次。API 滚动窗口会随重跑变化；诊断以旧缓存固定文件 SHA256 记录于 results.json 为准。api_evidence.json/coverage.json/merged_coverage.json/results.json/sensitivity.json/daily_returns.npz 为审计产物；raw/merged/ 保存每币实际合并小时线。目录自己的 .gitignore 排除 JSON/log/raw，仓库已有规则排除 npz；未提交数据、未改实盘代码。','','**不通过：数据长度不足；全期 maxT 不显著；每个高频档相位离散超过改善；没有跨年份子区间验证。当前证据不能批准提高频率。下一步必须先取得并审核两年同所真实小时成交数据，再重新冻结执行/信号时钟并复验。**']
(O/'REPORT.md').write_text('\n'.join(lines)+'\n')
