import json,glob,hashlib
from pathlib import Path
import numpy as np,pandas as pd
O=Path(__file__).resolve().parent;r=json.load(open(O/'results.json'));sk=json.load(open(O/'skew_snapshot.json'))
lines=['# 期权与波动率风险溢价：未找到通过五项检验的可交易新增边际','', '研究日期：2026-10-08。结论：BTC 有正的日频波动率差描述性证据；没有证明任何净期权策略或组合 Sharpe 改善。ETH 否决。只能验证溢价存在性，不能回测完整策略。','', '## 数据和时间对齐','', '已先阅读 docs/validation-protocol.md、src/trader.rs，另检查 src/store.rs。仓库中未找到用户提及的 common.md；采用明确指定的五项协议。未重复 23 个永续横截面方向。','', '公开 API 通过指定代理获取 BTC/ETH DVOL 日线、当前全部期权工具/行情摘要、近 30 天 ATM 与约 25 delta 盘口；保存完整原始响应。没有完整历史期权链、历史盘口或历史保证金路径。']
for c in ['BTC','ETH']:
 a=json.load(open(O/f'{c}_dvol.json'));t=pd.to_datetime([x[0] for x in a],unit='ms',utc=True)
 lines.append(f'- {c} DVOL：{len(a)} 根，{t.min()} 至 {t.max()}；最后未收盘日已剔除。')
lines+=['','DVOL 和 HL 日线的时间戳均为开盘时刻，收盘值推迟到次日 UTC 00:00 可观察时刻；未来 RV 仅使用之后 30 个完整日的 log return。RV = sqrt(365/30 × Σr²)，不减均值，适合描述方差结算；不是 30 日收益率的标准差。日频采样可能遗漏日内价格路径；无法代表连续对冲已实现方差。HL 价格不是 Deribit 指数，还存在跨所基差。期末 30 天没有未来标签，不使用。2023–24 子区间排除到期落入 2025 的窗口。','', '## 溢价：波动率差不等于期权收益','', '| 标的/区间 | 窗口数 | DVOL均值% | 后30日RV均值% | 差：波动率点 | 方差差 | IV>RV比例 | 30相位均值±SD（点） | 相位最小/最大 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|']
for c in ['BTC','ETH']:
 for p,v in r[c].items():
  mi,ma=v['phase_vol_gap_minmax_pp'];lines.append(f"| {c}/{p} | {v['n']} | {v['iv_pct']:.2f} | {v['future_rv_pct']:.2f} | {v['vol_gap_pp']:.2f} | {v['variance_gap']:.4f} | {v['positive_vol_gap_fraction']:.1%} | {v['phase_vol_gap_mean_pp']:.2f} ± {v['phase_vol_gap_sd_pp']:.2f} | {mi:.2f}/{ma:.2f} |")
lines+=['','方差差为 annualized IV² − annualized future RV²，无资金收益率单位。BTC 后段明显变薄；ETH 后段转负，且相位符号不稳。每相位按 UTC epoch day % 30 抽样，窗口不重叠，各相位全部报告在 results.json。未以最好相位替代平均。','', '## 多重检验和重叠','', '测试 8 个预设方向性统计量：BTC/ETH 各 4 个（平均波动率差、平均方差差、IV²−过去RV² 对未来RV²的增量预测、偏离均值回归）。没有策略参数网格，没有调仓/仓位优化。预测检验控制过去RV²，使用残差乘积的均值；回归斜率只作描述。均值回归检验使用未来偏离−当前偏离。','', '共同可用日期联合循环 moving-block bootstrap，4,000 次、seed=20261008；保留跨标的依赖。bootstrap 均值标准差作 SE，中心化零假设最大单侧标准化统计量作 maxT，控制这 8 项 FWER。60/90/120 天块长均报告，不选择最有利块长。子区间表仅描述，没有宣称子区间显著；全期均值在完整描述样本与8项共同样本略有差异，检验对应共同样本。','', '| 检验 | p_FWER 60d | p_FWER 90d | p_FWER 120d | 90d共同样本均值95%块CI |','|---|---:|---:|---:|---|']
for name,v in r['multiple_testing']['tests']['90'].items():
 vals=[r['multiple_testing']['tests'][str(L)][name]['p_fwer'] for L in [60,90,120]];ci=v['block_percentile_95_ci'];lines.append(f"| {name} | {vals[0]:.4f} | {vals[1]:.4f} | {vals[2]:.4f} | [{ci[0]:.5f}, {ci[1]:.5f}] |")
lines+=['','BTC 波动率差通过全期统计显著性，但更接近短方差经济机制的方差差在60/90天块长不通过；不能选择120天结果给它放行。BTC 预测关联通过全期检验，但没有独立样本预测或交易检验。两币偏离均值回归显著，然而过去RV与未来RV滚动变化有机械回归成分，不能把它解释为可收取的期权溢价。','', '## 期限结构、偏斜','', 'DVOL 本身只有固定30天一条序列，不能恢复历史期限结构或偏斜。当前链仅用于展示可采集的数据，不构成预测证据。ATM 每个到期日选最近标的价格的 strike，mark IV 不代表可成交 IV。']
for c in ['BTC','ETH']:
 near=[v for v in r['current_ATM_term_structure'][c] if 7<=v['days']<=100]
 lines.append(f"- {c} 当前期限（剩余天数/ATM mark IV%）："+'；'.join(f"{v['days']:.1f}/{v['atm_mark_iv_pct']:.2f}" for v in near if v['atm_mark_iv_pct'] is not None))
 x=sk[c];lines.append(f"- {c} 近30天约25-delta call−put mark IV：{x['call_minus_put_mark_iv_points']:.2f} 点；实际 delta "+'/'.join(f"{v['actual_delta']:.3f}" for v in x['legs'])+'。这是当天快照，不能评价独立预测力。')
lines+=['','## 成本与真实成交','', '只用当前真实买卖报价衡量小单成本：卖出取 bid，买回取 ask；不假设碰到就成交。快照非同时、报价可能撤单，实际应记录 IOC 成交、拒单及冲击。20档总深度不是最优价容量。maker 收益不回测：成交条件常与价格快速移动、IV重定价相关；短gamma头寸此时容易产生负对冲损益，必须测成交条件下后续 markout 与排队，不能用较低费率替代成交模型。','', '按当前标准档每腿手续费 min(0.03%标的名义,12.5%权利金)，用盘口 vega 将 (半价差+开仓费) 或 (全价差+往返费) 转成波动率点，近似线性、仅此时此合约。期权手续费不能套用HL永续费率。','', '| 合约 | bid/ask（币） | 开仓成本（vol点） | 往返成本（vol点） |','|---|---:|---:|---:|']
for c,rows in r['current_ATM_cost_snapshot'].items():
 for x in rows:lines.append(f"| {x['instrument']} | {x['bid']:.4f}/{x['ask']:.4f} | {x['entry_cost_vol_points']:.3f} | {x['roundtrip_cost_vol_points']:.3f} |")
lines+=['','同一数量call+put组合的成本/vega应用合计，不能把两腿vol点简单相加。BTC约1.61点往返。不能做5.05−1.61=3.44点的历史净VRP结论：DVOL是多strike两expiry的平滑方差指标，不是单个ATM权利金或variance strike，今日价差也不是历史价差。缺历史链后，净收益、年化换手/成本均无法可靠计算。持有至到期还需每腿至多0.015%标的的交割费（12.5%权利金上限）；每日到期期权有例外，具体见官方费用表。','', '若用HL永续对冲：净对冲费用=Σ|Δhedge_notional| × (0.045% taker+0.03%实测滑点)；maker名义费0.015%但不赋予自动成交。需要逐时/逐笔delta和资金费率，当前数据没有期权delta历史，不能估算真实换手或年化对冲成本。','', '## 与基线相关性','', '使用已有独立标量复核的 trader.rs 三因子目标与 next-open 执行基线（liq_oi_20261008）。全期三相位Sharpe约1.776/1.120/1.738，平均1.544；不以1.79强行缩放。cap5、当日20日样本波动和过去30日成交额口径与旧cap8历史标题不同。基线未纳入完整资金费率、下架缺价假定及最小订单额；这是研究复核，不是实盘收益审计。','', '诊断代理 a_t = mean(前30天DVOL²)/365 − r_t²，表示每日新建等份30天“假想方差合约”的日方差累计。用前一日已知IV；它没有交易标价、期权组合、保证金、IV的MTM或资本分母，绝不是日收益。基线收益标记日+1对齐收益已实现时点。','', '| 标的/区间 | 与基线3相位相关性 | 相位均值±SD |','|---|---|---|']
for c,periods in r['correlation_DIAGNOSTIC_ONLY'].items():
 for p,vs in periods.items():
  a=np.array([v['daily_proxy_correlation'] for v in vs]);lines.append(f"| {c}/{p} | "+'/'.join(f'{v:.3f}' for v in a)+f" | {a.mean():.3f} ± {a.std(ddof=1):.3f} |")
lines+=['','代理相关性较低，仅能说明日平方收益风险与研究基线关联不强；真实短vol策略危机时的相关性和尾部联合损失仍未知。未据此生成混合权重、代理Sharpe或组合Sharpe，以免把不可交易序列伪装成收益。两个子区间的真实期权净Sharpe及组合改善均无法给出，因此不满足第五项。','', '## 保证金、资金占用与容量','', '逆向BTC/ETH期权币本位定价结算，持有币抵押会带来币价风险，需要另行对冲。标准保证金ATM短call约0.15币+mark权利金，短put亦按官方含维持保证金的公式；两腿各1币名义的ATM短跨式，初始占用约0.30币+两腿mark，不是只投入收到的权利金。组合保证金按压力情景计算，不能假设固定倍数。','', '应按独立划拨权益（含缓冲、对冲保证金、抵押品汇率损益）计算日收益；另报告动态初始/维持保证金和压力资本收益率。跨所不能共享HL全仓保证金；新增资金或移出原策略资金须计机会成本。缺路径时，按名义或权利金计算Sharpe无效。','', '加密期权流动性集中BTC/ETH与少数到期日，容量有限。当前特定盘口不足以证明可长期承接规模；DVOL篮子包含尾部strike，复制容量往往更差。需用实际数量逐档吃单计算bid卖出收入及ask平仓成本，压力期评估撤单/滑点；20档合计不可视为单价容量。','', '## 不用期权账户能否近似','', '仅用永续动态delta调整可以做负gamma的“涨后买、跌后卖”，但没有卖期权时收取的初始权利金/隐含方差价格，因此不能凭空赚取IV>RV溢价。它只承担路径损失、资金费率和执行成本；网格/均值回归可能在某些路径赚钱，但不是复制同一个VRP。','', '数学复制需要确定的终端非线性负债、初始定价现金和连续自融资对冲，跳跃/离散对冲会留下误差。short DVOL futures的结算标的是未来隐含波动而非已实现方差，仍需其他衍生品账户，不能用DVOL−futureRV当其收益。永续carry、低波因子也不等价，本研究不重新测试已排除方向。','', '## 五项检验判定','', '| 检验 | 判定 |','|---|---|','| 全相位 | 30个持有期相位、3个基线相位均报告；ETH不稳 |','| 重叠 | 60/90/120d联合块bootstrap；无朴素t检验 |','| 真实成交 | 只有当前taker成本快照；历史真实成交不可验证，未通过 |','| 多重检验 | 8项maxT；BTC方差差块长不稳，不通过交易候选标准 |','| 成本、两子区间改善和相关性 | 实际净P&L/资本收益/组合改善不可计算；代理相关性不可代替，未通过 |','', '**通过五项检验的新策略数量：0。** BTC描述性VRP值得保存证据，但本次不能给实盘新增建议。','', '## 复现与文件','', '```bash','cd /Users/wonder/Code/stars','python research/vrp_20261008/fetch.py','python research/vrp_20261008/skew_snapshot.py','python research/vrp_20261008/analyze.py > research/vrp_20261008/run.log','python research/vrp_20261008/report.py','```','', '依赖Python、numpy、pandas、requests；baseline_returns.csv来自 research/liq_oi_20261008/check_baseline.py（按同目录engine.py）。fetch.py缓存历史DVOL块，但重跑当前链会更新快照；要复现本报告使用保存的raw而非重新抓取。results.json保留全部相位、检验、子样本、成本和相关性；aligned.csv可审计时间对齐；manifest.json保留原始文件sha256。','', '## 官方资料','', '- [DVOL 方法：30天、多strike两expiry、depth/trade/mark回退与平滑](https://insights.deribit.com/exchange-updates/dvol-deribit-implied-volatility-index/)','- [当前手续费与交割费](https://support.deribit.com/hc/en-us/articles/25944746248989-Fees)','- [逆向期权、标准保证金](https://support.deribit.com/hc/en-us/articles/31424939096093-Inverse-Options)','- [组合保证金压力模型](https://support.deribit.com/hc/en-us/articles/25944756247837-Portfolio-Margin)','- [DVOL期货结算为隐含波动指数](https://support.deribit.com/hc/en-us/articles/31424954825373-DVOL-Futures)']
(O/'REPORT.md').write_text('\n'.join(lines)+'\n')
paths=sorted((O/'raw').glob('*.json'))+[O/'BTC_dvol.json',O/'ETH_dvol.json',O.parent/'liq_oi_20261008/baseline_returns.csv',Path('/tmp/hl-daily-full/BTC.json'),Path('/tmp/hl-daily-full/ETH.json')]
json.dump({str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},open(O/'manifest.json','w'),indent=2)
print('report written',len(lines),'lines')
